// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFATqqiQV65xRdvGgMRPhq_CqDKfIAZg8',
    appId: '1:832297570081:web:826b8a9b4bfd29a27e7860',
    messagingSenderId: '832297570081',
    projectId: 'parental-control-app-7581f',
    authDomain: 'parental-control-app-7581f.firebaseapp.com',
    storageBucket: 'parental-control-app-7581f.firebasestorage.app',
    measurementId: 'G-GXSVSN9D87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ppv9ic-xGCQRTL6OK_rrMhALqaZKSeI',
    appId: '1:832297570081:android:324d70c4bdd93dea7e7860',
    messagingSenderId: '832297570081',
    projectId: 'parental-control-app-7581f',
    storageBucket: 'parental-control-app-7581f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfNAbaZFiOjrFyZ9f1Qw8zj2GNb2ECExE',
    appId: '1:832297570081:ios:5d1fcd5a2819781d7e7860',
    messagingSenderId: '832297570081',
    projectId: 'parental-control-app-7581f',
    storageBucket: 'parental-control-app-7581f.firebasestorage.app',
    iosBundleId: 'com.example.parentalControlApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfNAbaZFiOjrFyZ9f1Qw8zj2GNb2ECExE',
    appId: '1:832297570081:ios:5d1fcd5a2819781d7e7860',
    messagingSenderId: '832297570081',
    projectId: 'parental-control-app-7581f',
    storageBucket: 'parental-control-app-7581f.firebasestorage.app',
    iosBundleId: 'com.example.parentalControlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFATqqiQV65xRdvGgMRPhq_CqDKfIAZg8',
    appId: '1:832297570081:web:a1ee656d19ab6c067e7860',
    messagingSenderId: '832297570081',
    projectId: 'parental-control-app-7581f',
    authDomain: 'parental-control-app-7581f.firebaseapp.com',
    storageBucket: 'parental-control-app-7581f.firebasestorage.app',
    measurementId: 'G-8574JMZ7XF',
  );
}
